version: "3.7"

services: 
    db:
        image: postgres
        restart: always
        env_file: ./env/.env.development.db
        environment: 
            PGDATA: /var/lib/postgresql/data
        volumes: 
            - db-data:/var/lib/postgresql/data
        ports: 
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        env_file: ./env/.env.development
        ports:
            - "5555:80"
        volumes: 
            - pgadmin-data:/var/lib/pgadmin
        links: 
            - "db:pgsql-server"

volumes: 
    db-data:
    pgadmin-data: