version: '3.7'

services:
    web:
        build: 
            context: ./app
            dockerfile: Dockerfile.prod
        restart: always
        volumes:
            - static_volume:/home/app/web/staticfiles
            - ./certs:/etc/certs
            - ./requirements/:/usr/src/app/
            - ./env/:/home/app/web/env/
        expose:
            - 8000
        env_file:
            - ./env/.env.production
        depends_on:
            - db
    
    nginx:
        build: ./nginx
        restart: always
        env_file:
            - ./env/.env.production
        volumes:
            - static_volume:/home/app/web/staticfiles
            - ./certs:/etc/certs
        ports:
            - 443:443
            - 8080:80
        depends_on:
            - web

    db:
        image: postgres:12.0-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env/.env.production.db

volumes:
    postgres_data:
    static_volume: