# Generated by Django 3.2.5 on 2021-08-05 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=50)),
                ('income_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('income_date', models.DateField()),
                ('income_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomes.incomesgroup')),
                ('income_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
